import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const inter= Inter({subsets: ["latin"]})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className}`}
      ><Header/>
        {/* {header} */}
        <main className="min-h-screen">{children}</main>
        {/* {footer} */}
        <footer>
          <div>
            <p>
              Made by SAD.
            </p>
          </div>
        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
